service: auth-sls

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    JWT_KEY: sam123

plugins:
  - serverless-offline

functions:
  authorizer-func:
    handler: src/authorizer.handler
  login:
    handler: src/login.handler
    events:
      - http:
          path: login
          method: post
          cors: true
  heroes-public:
    handler: src/getHeroes.public
    events:
      - http:
          path: public
          method: get
          cors:
            - '*'
          headers:
            - Content-Type
            - Authorization
  heroes-private:
    handler: src/getHeroes.private
    events:
      - http:
          path: private
          method: get
          authorizer: authorizer-func
          cors:
            - '*'
          headers:
            - Content-Type
            - Authorization